#!/usr/bin/env python

from zensols.cli import ConfigurationImporterCliHarness

if (__name__ == '__main__'):
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.zotsite.ApplicationFactory',
        #config_path='test-resources/zotsite.conf',
        proto_args='export -o target/site',
        proto_factory_kwargs={'reload_pattern': r'^zensols.zotsite'},
    )
    harness.run()
